import type { Metadata } from "next"; import Link from "next/link";
export const metadata: Metadata = { title:"FAQ" };
const FAQS = [
  ["What is the best time to visit Kenya?","Kenya has excellent wildlife viewing year-round. The Great Wildebeest Migration peaks in the Maasai Mara from July to October. The dry seasons (January�February and June) are ideal for game viewing. December is festive season with excellent wildlife and higher rates."],
  ["Do I need to be physically fit?","Standard game drive safaris are accessible to most fitness levels � you spend the majority of time seated. Walking safaris require a reasonable level of fitness. We discuss physical considerations during planning."],
  ["How many people in my vehicle?","Mid-range and luxury properties typically carry 4�7 guests per vehicle. Private vehicle upgrades are available and strongly recommended for honeymoons, families, and photographers."],
  ["How do I book?","Submit your enquiry through our Plan a Safari form. A specialist responds within 4 hours with an initial proposal. A 30% deposit confirms your booking."],
  ["What is your deposit policy?","30% deposit within 72 hours of receiving your confirmed quotation. Balance due 60 days prior to arrival. For bookings within 60 days of travel, full payment is required at booking."],
  ["Do I need travel insurance?","Yes � we require proof of travel insurance including emergency medical evacuation cover before final confirmation. A helicopter evacuation from a remote safari location can cost USD 15,000�50,000 without insurance."],
  ["Do I need a visa for Kenya?","Kenya operates an electronic Travel Authorisation (eTA) system at etakenya.go.ke. Most nationalities pay USD 30. Apply at least two weeks before travel."],
  ["What should I pack?","Neutral colours (khaki, olive, beige) for game drives. Layers for cool mornings. Wide-brimmed hat, sunscreen SPF50+, good binoculars. We send a detailed packing list with your booking confirmation."],
  ["What is KATO bonding?","KATO (Kenya Association of Tour Operators) operates a client protection fund that insures your payments against company failure. Booking with a KATO-bonded operator is the international standard of travel protection for Kenya safaris."],
  ["Is Kenya safe?","Kenya is a well-established safari destination welcoming hundreds of thousands of international visitors annually. The wildlife areas we operate in are safe. We monitor conditions continuously and communicate proactively with confirmed clients."]
];
export default function FAQPage() {
  return (<><section className="bg-rima-jungle py-20 px-[var(--section-px)]"><div className="max-w-[var(--content-max)] mx-auto text-center"><p className="eyebrow text-rima-gold mb-4">HELP</p><h1 className="font-serif text-white font-light" style={{ fontSize:"clamp(2rem,5vw,3.5rem)" }}>Frequently Asked <em style={{ color:"var(--rima-gold)" }}>Questions</em></h1></div></section><section className="section-wrapper"><div className="content-width max-w-3xl mx-auto"><div className="divide-y" style={{ borderColor:"var(--rima-cream-dark)" }}>{FAQS.map(([q,a]) => (<details key={q} className="group py-5"><summary className="flex items-center justify-between cursor-pointer list-none"><h3 className="font-sans font-medium pr-8" style={{ color:"var(--rima-dark)", fontSize:"0.9375rem" }}>{q}</h3><span className="shrink-0 text-rima-gold text-xl group-open:rotate-45 transition-transform">+</span></summary><p className="mt-4 font-sans" style={{ color:"var(--rima-gray)", fontSize:"0.9375rem", lineHeight:1.8 }}>{a}</p></details>))}</div><div className="mt-16 p-8 text-center" style={{ background:"var(--rima-cream)" }}><p className="font-sans mb-4" style={{ color:"var(--rima-earth)" }}>Still have a question?</p><a href="https://wa.me/254714728554" target="_blank" rel="noopener noreferrer" className="btn-primary">Chat on WhatsApp</a></div></div></section></>);
}
